package pe.edu.upc.easyvet.core.designsystem.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006B5F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF3ED6C1)
val onPrimaryContainerLight = Color(0xFF00594F)
val secondaryLight = Color(0xFF36675E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB7EADF)
val onSecondaryContainerLight = Color(0xFF3B6B63)
val tertiaryLight = Color(0xFF5F5695)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC3B8FF)
val onTertiaryContainerLight = Color(0xFF4F4684)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF4FBF8)
val onBackgroundLight = Color(0xFF161D1B)
val surfaceLight = Color(0xFFF4FBF8)
val onSurfaceLight = Color(0xFF161D1B)
val surfaceVariantLight = Color(0xFFD7E6E1)
val onSurfaceVariantLight = Color(0xFF3C4A46)
val outlineLight = Color(0xFF6C7A76)
val outlineVariantLight = Color(0xFFBBCAC5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3230)
val inverseOnSurfaceLight = Color(0xFFEBF2EF)
val inversePrimaryLight = Color(0xFF47DCC7)
val surfaceDimLight = Color(0xFFD5DCD9)
val surfaceBrightLight = Color(0xFFF4FBF8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEEF5F2)
val surfaceContainerLight = Color(0xFFE8EFEC)
val surfaceContainerHighLight = Color(0xFFE3EAE7)
val surfaceContainerHighestLight = Color(0xFFDDE4E1)


val primaryDark = Color(0xFF63F3DD)
val onPrimaryDark = Color(0xFF003731)
val primaryContainerDark = Color(0xFF3ED6C1)
val onPrimaryContainerDark = Color(0xFF00594F)
val secondaryDark = Color(0xFF9ED0C6)
val onSecondaryDark = Color(0xFF003731)
val secondaryContainerDark = Color(0xFF1C4F47)
val onSecondaryContainerDark = Color(0xFF8DBFB5)
val tertiaryDark = Color(0xFFDFD8FF)
val onTertiaryDark = Color(0xFF312764)
val tertiaryContainerDark = Color(0xFFC3B8FF)
val onTertiaryContainerDark = Color(0xFF4F4684)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E1513)
val onBackgroundDark = Color(0xFFDDE4E1)
val surfaceDark = Color(0xFF0E1513)
val onSurfaceDark = Color(0xFFDDE4E1)
val surfaceVariantDark = Color(0xFF3C4A46)
val onSurfaceVariantDark = Color(0xFFBBCAC5)
val outlineDark = Color(0xFF859490)
val outlineVariantDark = Color(0xFF3C4A46)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDDE4E1)
val inverseOnSurfaceDark = Color(0xFF2B3230)
val inversePrimaryDark = Color(0xFF006B5F)
val surfaceDimDark = Color(0xFF0E1513)
val surfaceBrightDark = Color(0xFF343B39)
val surfaceContainerLowestDark = Color(0xFF090F0E)
val surfaceContainerLowDark = Color(0xFF161D1B)
val surfaceContainerDark = Color(0xFF1A211F)
val surfaceContainerHighDark = Color(0xFF242B2A)
val surfaceContainerHighestDark = Color(0xFF2F3634)






